// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Myggiz AB

//! Thin wrapper over `openmls::group::MlsGroup`.

use openmls::group::{MlsGroupJoinConfig, StagedWelcome};
use openmls::prelude::*;
use openmls::prelude::{ProcessedMessageContent, ProtocolMessage};
use openmls::schedule::psk::PreSharedKeyId;
use tls_codec::{Deserialize as _, Serialize as _};

use crate::envelope::Envelope;
use crate::error::{CoreError, Result};
use crate::identity::IdentityKey;
use crate::mls::key_package::{
    credential_with_key, signer_from_identity, KeyPackage, MLS_CIPHERSUITE,
};
use crate::mls::provider::MlsProvider;
use crate::mls::state_machine::GroupState;
use crate::storage::MlsGroupRepo;

/// Opaque MLS group id (variable-length bytes generated by OpenMLS).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GroupId(pub Vec<u8>);

/// Opaque Welcome blob.
pub type WelcomeBytes = Vec<u8>;

/// Opaque Commit blob.
pub type CommitBytes = Vec<u8>;

/// A single MLS group from our perspective.
pub struct Group {
    id: GroupId,
    state: GroupState,
    provider: MlsProvider,
    inner: openmls::group::MlsGroup,
}

impl Group {
    /// Create a fresh single-member group.
    pub(crate) fn create_solo(
        identity: &IdentityKey,
        psk: Option<&[u8; 32]>,
        provider: MlsProvider,
    ) -> Result<Self> {
        let signer = signer_from_identity(identity, &provider)?;
        let cwk = credential_with_key(identity, &signer);

        let group_create_config = MlsGroupCreateConfig::builder()
            .ciphersuite(MLS_CIPHERSUITE)
            .use_ratchet_tree_extension(true)
            .build();

        let inner = openmls::group::MlsGroup::new(
            provider.as_openmls(),
            &signer,
            &group_create_config,
            cwk,
        )
        .map_err(|e| CoreError::Mls(format!("mls: builder: {e:?}")))?;

        let gid = GroupId(inner.group_id().to_vec());

        if let Some(psk_bytes) = psk {
            register_external_psk(&provider, psk_bytes)?;
        }

        Ok(Self {
            id: gid,
            state: GroupState::Active { epoch: 0 },
            provider,
            inner,
        })
    }

    pub(crate) fn add_member(
        &mut self,
        invitee_kp: &KeyPackage,
        psk: Option<&[u8; 32]>,
    ) -> Result<(WelcomeBytes, CommitBytes)> {
        // Guard against 3rd member (2-member only for 1.C).
        if self.inner.members().count() >= 2 {
            return Err(CoreError::Mls("mls: add_member: already 2-member".into()));
        }

        if let Some(psk_bytes) = psk {
            let psk_id = register_external_psk(&self.provider, psk_bytes)?;
            let signer = load_signer(&self.provider, &own_public_key(&self.inner)?)?;
            self.inner
                .propose_external_psk(self.provider.as_openmls(), &signer, psk_id)
                .map_err(|e| CoreError::Mls(format!("mls: propose external psk: {e:?}")))?;
        }

        let signer = load_signer(&self.provider, &own_public_key(&self.inner)?)?;

        // OpenMLS 0.8.1 returns (commit, welcome, group_info).
        let (commit_out, welcome_out, _group_info) = self
            .inner
            .add_members(
                self.provider.as_openmls(),
                &signer,
                &[invitee_kp.as_openmls().clone()],
            )
            .map_err(|e| CoreError::Mls(format!("mls: add_members: {e:?}")))?;

        // Merge the staged Commit *before* shipping — 2-member has no
        // conflicting proposal source. Phase 2's PendingCommit state
        // removes this eager-merge.
        self.inner
            .merge_pending_commit(self.provider.as_openmls())
            .map_err(|e| CoreError::Mls(format!("mls: merge_pending_commit: {e:?}")))?;

        let welcome_bytes = welcome_out
            .tls_serialize_detached()
            .map_err(|e| CoreError::Mls(format!("mls: welcome serialize: {e}")))?;
        let commit_bytes = commit_out
            .tls_serialize_detached()
            .map_err(|e| CoreError::Mls(format!("mls: commit serialize: {e}")))?;

        self.state = GroupState::Active {
            epoch: self.inner.epoch().as_u64(),
        };
        Ok((welcome_bytes, commit_bytes))
    }

    pub(crate) fn join_from_welcome(
        identity: &IdentityKey,
        welcome: &[u8],
        psk: Option<&[u8; 32]>,
        provider: MlsProvider,
    ) -> Result<Self> {
        // Ensure the signer is registered in this provider so OpenMLS can
        // verify our own leaf in later ops. The signer may already be stored
        // if KeyPackage::generate was called with the same provider — ignore
        // the "already present" error and proceed.
        let _ = signer_from_identity(identity, &provider);

        if let Some(psk_bytes) = psk {
            register_external_psk(&provider, psk_bytes)?;
        }

        let welcome_msg = MlsMessageIn::tls_deserialize_exact(welcome)
            .map_err(|e| CoreError::Mls(format!("mls: welcome deserialize: {e}")))?;
        let welcome_inner = match welcome_msg.extract() {
            MlsMessageBodyIn::Welcome(w) => w,
            _ => return Err(CoreError::Mls("mls: welcome: wrong message type".into())),
        };

        // Note: welcome_inner.ciphersuite() is pub(crate) in openmls 0.8.1 and
        // cannot be accessed externally. Ciphersuite is validated implicitly by
        // StagedWelcome::new_from_welcome rejecting unknown suites.

        let join_config = MlsGroupJoinConfig::builder()
            .use_ratchet_tree_extension(true)
            .build();

        let staged = StagedWelcome::new_from_welcome(
            provider.as_openmls(),
            &join_config,
            welcome_inner,
            None,
        )
        .map_err(|e| CoreError::Mls(format!("mls: welcome process: {e:?}")))?;

        let inner = staged
            .into_group(provider.as_openmls())
            .map_err(|e| CoreError::Mls(format!("mls: welcome into_group: {e:?}")))?;

        let gid = GroupId(inner.group_id().to_vec());
        let epoch = inner.epoch().as_u64();
        Ok(Self {
            id: gid,
            state: GroupState::Active { epoch },
            provider,
            inner,
        })
    }

    pub(crate) fn encrypt(&mut self, envelope: &Envelope) -> Result<Vec<u8>> {
        if !self.state.can_send() {
            return Err(CoreError::Mls(format!(
                "mls: encrypt: invalid state {:?}",
                self.state
            )));
        }

        let signer = load_signer(&self.provider, &own_public_key(&self.inner)?)?;
        let plaintext = envelope.encode()?;

        let out = self
            .inner
            .create_message(self.provider.as_openmls(), &signer, &plaintext)
            .map_err(|e| CoreError::Mls(format!("mls: encrypt: {e:?}")))?;

        out.tls_serialize_detached()
            .map_err(|e| CoreError::Mls(format!("mls: encrypt: serialize: {e}")))
    }

    pub(crate) fn decrypt(&mut self, ciphertext: &[u8]) -> Result<Envelope> {
        if !self.state.can_send() {
            return Err(CoreError::Mls(format!(
                "mls: decrypt: invalid state {:?}",
                self.state
            )));
        }

        let msg_in = MlsMessageIn::tls_deserialize_exact(ciphertext)
            .map_err(|e| CoreError::Mls(format!("mls: decrypt: deserialize: {e}")))?;
        let protocol_message: ProtocolMessage = match msg_in.extract() {
            MlsMessageBodyIn::PrivateMessage(pm) => pm.into(),
            MlsMessageBodyIn::PublicMessage(pm) => pm.into(),
            _ => {
                return Err(CoreError::Mls(
                    "mls: decrypt: unsupported message type".into(),
                ))
            }
        };

        let processed = self
            .inner
            .process_message(self.provider.as_openmls(), protocol_message)
            .map_err(|e| CoreError::Mls(format!("mls: authentication failed: {e:?}")))?;

        let plaintext_bytes = match processed.into_content() {
            ProcessedMessageContent::ApplicationMessage(app) => app.into_bytes(),
            ProcessedMessageContent::StagedCommitMessage(_) => {
                return Err(CoreError::Mls(
                    "mls: decrypt: received Commit on encrypt path — route to process_incoming_commit"
                        .into(),
                ));
            }
            ProcessedMessageContent::ProposalMessage(_) => {
                return Err(CoreError::Mls("mls: decrypt: received Proposal".into()));
            }
            ProcessedMessageContent::ExternalJoinProposalMessage(_) => {
                return Err(CoreError::Mls(
                    "mls: decrypt: received ExternalJoinProposal".into(),
                ));
            }
        };

        Envelope::decode(&plaintext_bytes)
    }

    pub(crate) fn process_incoming_commit(&mut self, commit: &[u8]) -> Result<()> {
        let msg_in = MlsMessageIn::tls_deserialize_exact(commit)
            .map_err(|e| CoreError::Mls(format!("mls: process_commit: deserialize: {e}")))?;
        let protocol_message: ProtocolMessage = match msg_in.extract() {
            MlsMessageBodyIn::PublicMessage(pm) => pm.into(),
            MlsMessageBodyIn::PrivateMessage(pm) => pm.into(),
            _ => {
                return Err(CoreError::Mls(
                    "mls: process_commit: wrong message type".into(),
                ));
            }
        };

        let processed = self
            .inner
            .process_message(self.provider.as_openmls(), protocol_message)
            .map_err(|e| CoreError::Mls(format!("mls: authentication failed: {e:?}")))?;

        match processed.into_content() {
            ProcessedMessageContent::StagedCommitMessage(staged) => {
                self.inner
                    .merge_staged_commit(self.provider.as_openmls(), *staged)
                    .map_err(|e| CoreError::Mls(format!("mls: merge_staged_commit: {e:?}")))?;
                self.state = GroupState::Active {
                    epoch: self.inner.epoch().as_u64(),
                };
                Ok(())
            }
            _ => Err(CoreError::Mls(
                "mls: process_commit: not a Commit message".into(),
            )),
        }
    }

    pub(crate) fn advance_epoch(&mut self) -> Result<Vec<u8>> {
        if !self.state.can_send() {
            return Err(CoreError::Mls(format!(
                "mls: advance_epoch: invalid state {:?}",
                self.state
            )));
        }

        let signer = load_signer(&self.provider, &own_public_key(&self.inner)?)?;
        let bundle = self
            .inner
            .self_update(
                self.provider.as_openmls(),
                &signer,
                LeafNodeParameters::default(),
            )
            .map_err(|e| CoreError::Mls(format!("mls: self_update: {e:?}")))?;

        let (commit_out, _welcome_opt, _group_info_opt) = bundle.into_messages();

        self.inner
            .merge_pending_commit(self.provider.as_openmls())
            .map_err(|e| CoreError::Mls(format!("mls: merge_pending_commit: {e:?}")))?;

        let bytes = commit_out
            .tls_serialize_detached()
            .map_err(|e| CoreError::Mls(format!("mls: advance_epoch: serialize: {e}")))?;
        self.state = GroupState::Active {
            epoch: self.inner.epoch().as_u64(),
        };
        Ok(bytes)
    }

    /// Persist current state. Writes the `(group_id, state_blob, epoch)`
    /// row via `MlsGroupRepo::put`. `state_blob` is the ciborium-encoded
    /// provider snapshot (HashMap of all OpenMLS internal state).
    pub(crate) fn save(&self, repo: &MlsGroupRepo<'_>) -> Result<()> {
        let blob = self.provider.snapshot()?;
        repo.put(&self.id.0, &blob, self.inner.epoch().as_u64())
    }

    /// Restore from persisted state. Returns `None` if `group_id` is unknown.
    pub(crate) fn load(group_id: &GroupId, repo: &MlsGroupRepo<'_>) -> Result<Option<Self>> {
        let Some(blob) = repo.get(&group_id.0)? else {
            return Ok(None);
        };
        let provider = MlsProvider::load(&blob)?;
        let openmls_gid = openmls::prelude::GroupId::from_slice(&group_id.0);
        let inner = openmls::group::MlsGroup::load(provider.as_openmls().storage(), &openmls_gid)
            .map_err(|e| CoreError::Mls(format!("mls: load: {e:?}")))?
            .ok_or_else(|| CoreError::Mls("mls: load: corrupt state blob".into()))?;

        Ok(Some(Self {
            id: group_id.clone(),
            state: GroupState::Active {
                epoch: inner.epoch().as_u64(),
            },
            provider,
            inner,
        }))
    }

    /// Returns the group identifier.
    #[must_use]
    pub fn id(&self) -> &GroupId {
        &self.id
    }

    /// Returns the current MLS epoch number.
    #[must_use]
    pub fn epoch(&self) -> u64 {
        self.inner.epoch().as_u64()
    }

    /// Returns the current group state.
    #[must_use]
    pub fn state(&self) -> &GroupState {
        &self.state
    }
}

/// Re-materialize the `SignatureKeyPair` stored in this provider by
/// public key. OpenMLS state-advancing calls require a `&impl Signer`;
/// we reconstruct it from storage rather than threading a long-lived
/// reference through `Group`.
fn load_signer(
    provider: &MlsProvider,
    public_key: &[u8],
) -> Result<openmls_basic_credential::SignatureKeyPair> {
    openmls_basic_credential::SignatureKeyPair::read(
        provider.as_openmls().storage(),
        public_key,
        openmls::prelude::SignatureScheme::ED25519,
    )
    .ok_or_else(|| CoreError::Mls("mls: load_signer: missing signer".into()))
}

/// Extract our own signature public key from the group.
fn own_public_key(group: &openmls::group::MlsGroup) -> Result<Vec<u8>> {
    let own_leaf = group
        .own_leaf_node()
        .ok_or_else(|| CoreError::Mls("mls: own_public_key: no own leaf".into()))?;
    Ok(own_leaf.signature_key().as_slice().to_vec())
}

/// The external-PSK identifier byte string. Matches the HKDF label from
/// 1.B so the two layers use the same constant. Both sides must register
/// a PSK under this identifier for the Add Commit's PSK proposal to
/// decrypt on the other side.
const PSK_ID_BYTES: &[u8] = b"skattr-binding-v1";

/// Register a 32-byte external PSK with the provider under the
/// canonical Skattr PSK identifier. Returns a `PreSharedKeyId` that
/// the caller embeds in the Commit's PSK proposal (inviter side) or
/// that gets derived from the Welcome (invitee side).
fn register_external_psk(provider: &MlsProvider, psk: &[u8; 32]) -> Result<PreSharedKeyId> {
    let psk_id = PreSharedKeyId::external(PSK_ID_BYTES.to_vec(), vec![0u8; 32]);
    psk_id
        .store(provider.as_openmls(), psk)
        .map_err(|e| CoreError::Mls(format!("mls: psk register: {e:?}")))?;
    Ok(psk_id)
}

/// Public entry points for the `test-harness` feature — allow integration
/// tests in `crates/tests` to drive a `Group` end-to-end without exposing
/// the full API to production callers.
#[cfg(feature = "test-harness")]
impl Group {
    /// Public alias for [`Group::create_solo`] under `test-harness`.
    pub fn test_create_solo(
        identity: &IdentityKey,
        psk: Option<&[u8; 32]>,
        provider: MlsProvider,
    ) -> Result<Self> {
        Self::create_solo(identity, psk, provider)
    }

    /// Public alias for [`Group::add_member`] under `test-harness`.
    pub fn test_add_member(
        &mut self,
        invitee_kp: &KeyPackage,
        psk: Option<&[u8; 32]>,
    ) -> Result<(WelcomeBytes, CommitBytes)> {
        self.add_member(invitee_kp, psk)
    }

    /// Public alias for [`Group::join_from_welcome`] under `test-harness`.
    pub fn test_join_from_welcome(
        identity: &IdentityKey,
        welcome: &[u8],
        psk: Option<&[u8; 32]>,
        provider: MlsProvider,
    ) -> Result<Self> {
        Self::join_from_welcome(identity, welcome, psk, provider)
    }

    /// Public alias for [`Group::encrypt`] under `test-harness`.
    pub fn test_encrypt(&mut self, envelope: &crate::envelope::Envelope) -> Result<Vec<u8>> {
        self.encrypt(envelope)
    }

    /// Public alias for [`Group::decrypt`] under `test-harness`.
    pub fn test_decrypt(&mut self, ciphertext: &[u8]) -> Result<crate::envelope::Envelope> {
        self.decrypt(ciphertext)
    }

    /// Public alias for [`Group::save`] under `test-harness`.
    pub fn test_save(&self, repo: &MlsGroupRepo<'_>) -> Result<()> {
        self.save(repo)
    }

    /// Public alias for [`Group::load`] under `test-harness`.
    pub fn test_load(group_id: &GroupId, repo: &MlsGroupRepo<'_>) -> Result<Option<Self>> {
        Self::load(group_id, repo)
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::storage::Pool;

    fn alice() -> IdentityKey {
        IdentityKey::generate().unwrap()
    }

    #[test]
    fn create_solo_is_active_at_epoch_0() {
        let id = alice();
        let g = Group::create_solo(&id, None, MlsProvider::new()).unwrap();
        assert_eq!(g.epoch(), 0);
        assert!(matches!(g.state(), GroupState::Active { epoch: 0 }));
        assert!(!g.id().0.is_empty(), "group id must be set");
    }

    #[test]
    fn save_load_round_trip_preserves_epoch_and_id() {
        let pool = Pool::in_memory();
        let repo = MlsGroupRepo::new(&pool);
        let id = alice();

        let g = Group::create_solo(&id, None, MlsProvider::new()).unwrap();
        let gid = g.id().clone();
        g.save(&repo).unwrap();

        drop(g);

        let restored = Group::load(&gid, &repo).unwrap().expect("must load");
        assert_eq!(restored.epoch(), 0);
        assert_eq!(restored.id(), &gid);
    }

    #[test]
    fn load_missing_group_returns_none() {
        let pool = Pool::in_memory();
        let repo = MlsGroupRepo::new(&pool);
        let gid = GroupId(vec![0x99; 32]);
        assert!(Group::load(&gid, &repo).unwrap().is_none());
    }

    #[test]
    fn load_rejects_corrupt_blob() {
        let pool = Pool::in_memory();
        let repo = MlsGroupRepo::new(&pool);
        let gid = GroupId(vec![0xAA; 32]);
        repo.put(&gid.0, &[0xFFu8; 32], 7).unwrap();
        let err = match Group::load(&gid, &repo) {
            Ok(_) => panic!("garbage must fail"),
            Err(e) => e,
        };
        match err {
            CoreError::Mls(s) => assert!(s.starts_with("mls: load") || s.starts_with("mls:")),
            other => panic!("expected CoreError::Mls, got {other:?}"),
        }
    }

    #[test]
    fn add_member_emits_welcome_and_commit_and_bumps_epoch_to_1() {
        let pool = Pool::in_memory();
        let kp_repo = crate::storage::KeyPackageRepo::new(&pool);

        let alice_id = alice();
        let bob_id = IdentityKey::generate().unwrap();
        let bob_provider = MlsProvider::new();
        let bob_kp = KeyPackage::generate(&bob_id, &bob_provider, &kp_repo).unwrap();

        let mut alice = Group::create_solo(&alice_id, None, MlsProvider::new()).unwrap();
        assert_eq!(alice.epoch(), 0);

        let (welcome, commit) = alice.add_member(&bob_kp, None).unwrap();
        assert!(!welcome.is_empty());
        assert!(!commit.is_empty());
        assert_eq!(alice.epoch(), 1);
        assert!(matches!(alice.state(), GroupState::Active { epoch: 1 }));
    }

    #[test]
    fn join_from_welcome_lands_at_epoch_1_with_matching_group_id() {
        let pool = Pool::in_memory();
        let kp_repo = crate::storage::KeyPackageRepo::new(&pool);

        let alice_id = alice();
        let bob_id = IdentityKey::generate().unwrap();
        let bob_provider = MlsProvider::new();
        let bob_kp = KeyPackage::generate(&bob_id, &bob_provider, &kp_repo).unwrap();

        let mut alice = Group::create_solo(&alice_id, None, MlsProvider::new()).unwrap();
        let (welcome, _commit) = alice.add_member(&bob_kp, None).unwrap();

        let bob = Group::join_from_welcome(&bob_id, &welcome, None, bob_provider).unwrap();

        assert_eq!(bob.epoch(), 1);
        assert_eq!(bob.id(), alice.id(), "both sides see the same group id");
        assert!(matches!(bob.state(), GroupState::Active { epoch: 1 }));
    }

    fn pair_no_psk() -> (Group, Group) {
        let pool = Pool::in_memory();
        let kp_repo = crate::storage::KeyPackageRepo::new(&pool);
        let alice_id = alice();
        let bob_id = IdentityKey::generate().unwrap();
        let bob_provider = MlsProvider::new();
        let bob_kp = KeyPackage::generate(&bob_id, &bob_provider, &kp_repo).unwrap();
        let mut alice = Group::create_solo(&alice_id, None, MlsProvider::new()).unwrap();
        let (welcome, _commit) = alice.add_member(&bob_kp, None).unwrap();
        let bob = Group::join_from_welcome(&bob_id, &welcome, None, bob_provider).unwrap();
        (alice, bob)
    }

    fn test_envelope(text: &str) -> Envelope {
        use crate::envelope::{Kind, MessageId};
        Envelope {
            v: 1,
            id: MessageId::generate(),
            ts: 0,
            reply_to: None,
            kind: Kind::Text {
                body: text.to_string(),
            },
        }
    }

    #[test]
    fn bidirectional_encrypt_decrypt() {
        let (mut alice, mut bob) = pair_no_psk();

        let msg_a = test_envelope("hi from alice");
        let ct_a = alice.encrypt(&msg_a).unwrap();
        let got_a = bob.decrypt(&ct_a).unwrap();
        assert_eq!(format!("{got_a:?}"), format!("{msg_a:?}"));

        let msg_b = test_envelope("hi from bob");
        let ct_b = bob.encrypt(&msg_b).unwrap();
        let got_b = alice.decrypt(&ct_b).unwrap();
        assert_eq!(format!("{got_b:?}"), format!("{msg_b:?}"));
    }

    fn pair_with_psk(psk_alice: [u8; 32], psk_bob: [u8; 32]) -> Result<(Group, Group)> {
        let pool = Pool::in_memory();
        let kp_repo = crate::storage::KeyPackageRepo::new(&pool);
        let alice_id = alice();
        let bob_id = IdentityKey::generate().unwrap();
        let bob_provider = MlsProvider::new();
        let bob_kp = KeyPackage::generate(&bob_id, &bob_provider, &kp_repo)?;
        let mut alice = Group::create_solo(&alice_id, Some(&psk_alice), MlsProvider::new())?;
        let (welcome, _commit) = alice.add_member(&bob_kp, Some(&psk_alice))?;
        let bob = Group::join_from_welcome(&bob_id, &welcome, Some(&psk_bob), bob_provider)?;
        Ok((alice, bob))
    }

    #[test]
    fn external_psk_match_succeeds() {
        let psk = [0xEEu8; 32];
        let (alice, bob) = pair_with_psk(psk, psk).unwrap();
        assert_eq!(alice.epoch(), 1);
        assert_eq!(bob.epoch(), 1);
        assert_eq!(alice.id(), bob.id());
    }

    #[test]
    fn external_psk_mismatch_fails_on_bob_join() {
        let result = pair_with_psk([0xAAu8; 32], [0xBBu8; 32]);
        let err = match result {
            Ok(_) => panic!("mismatched PSK must fail"),
            Err(e) => e,
        };
        match err {
            CoreError::Mls(s) => {
                assert!(
                    s.contains("external PSK mismatch")
                        || s.contains("authentication")
                        || s.contains("welcome process"),
                    "unexpected message: {s}"
                );
            }
            other => panic!("expected CoreError::Mls, got {other:?}"),
        }
    }

    #[test]
    fn no_psk_path_still_works() {
        let pool = Pool::in_memory();
        let kp_repo = crate::storage::KeyPackageRepo::new(&pool);
        let alice_id = alice();
        let bob_id = IdentityKey::generate().unwrap();
        let bob_provider = MlsProvider::new();
        let bob_kp = KeyPackage::generate(&bob_id, &bob_provider, &kp_repo).unwrap();
        let mut alice = Group::create_solo(&alice_id, None, MlsProvider::new()).unwrap();
        let (welcome, _commit) = alice.add_member(&bob_kp, None).unwrap();
        let bob = Group::join_from_welcome(&bob_id, &welcome, None, bob_provider).unwrap();
        assert_eq!(alice.epoch(), 1);
        assert_eq!(bob.epoch(), 1);
    }

    #[test]
    fn advance_epoch_bumps_epoch_and_both_sides_ratchet() {
        let (mut alice, mut bob) = pair_no_psk();
        assert_eq!(alice.epoch(), 1);
        assert_eq!(bob.epoch(), 1);

        let commit = alice.advance_epoch().unwrap();
        assert_eq!(alice.epoch(), 2);

        bob.process_incoming_commit(&commit).unwrap();
        assert_eq!(bob.epoch(), 2);

        // Both sides can still encrypt/decrypt at epoch 2.
        let env = test_envelope("post-PCS");
        let ct = alice.encrypt(&env).unwrap();
        let got = bob.decrypt(&ct).unwrap();
        assert_eq!(format!("{got:?}"), format!("{env:?}"));
    }

    #[test]
    fn add_member_rejects_when_already_2_member() {
        let pool = Pool::in_memory();
        let kp_repo = crate::storage::KeyPackageRepo::new(&pool);
        let (mut alice, _bob) = pair_no_psk();

        let charlie_id = IdentityKey::generate().unwrap();
        let charlie_provider = MlsProvider::new();
        let charlie_kp = KeyPackage::generate(&charlie_id, &charlie_provider, &kp_repo).unwrap();

        let err = match alice.add_member(&charlie_kp, None) {
            Ok(_) => panic!("must reject 3rd"),
            Err(e) => e,
        };
        match err {
            CoreError::Mls(s) => assert!(s.contains("already 2-member"), "got: {s}"),
            other => panic!("expected CoreError::Mls, got {other:?}"),
        }
    }

    #[test]
    fn encrypt_rejects_corrupt_state() {
        let (mut alice, _bob) = pair_no_psk();
        // Force corrupt state directly (private field access via the
        // same module).
        alice.state = GroupState::Corrupt {
            reason: "forced for test".into(),
        };
        let env = test_envelope("should fail");
        let err = match alice.encrypt(&env) {
            Ok(_) => panic!("corrupt must reject"),
            Err(e) => e,
        };
        match err {
            CoreError::Mls(s) => assert!(s.starts_with("mls: encrypt: invalid state")),
            other => panic!("expected CoreError::Mls, got {other:?}"),
        }
    }

    #[test]
    fn advance_epoch_rejects_corrupt_state() {
        let (mut alice, _bob) = pair_no_psk();
        alice.state = GroupState::Corrupt {
            reason: "forced".into(),
        };
        let err = match alice.advance_epoch() {
            Ok(_) => panic!("corrupt must reject"),
            Err(e) => e,
        };
        match err {
            CoreError::Mls(s) => assert!(s.starts_with("mls: advance_epoch: invalid state")),
            other => panic!("expected CoreError::Mls, got {other:?}"),
        }
    }
}
