// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Myggiz AB

//! Thin wrapper over `openmls::MlsGroup`.
//!
//! Exposed operations are the minimal set `core` needs: create, add,
//! remove, leave, process Welcome/Commit, encrypt, decrypt. All state
//! transitions go through [`super::state_machine::GroupState`] so the
//! caller can never operate on a group in an inconsistent phase.

use crate::envelope::Envelope;
use crate::error::Result;
use crate::identity::PublicKey;
use crate::mls::state_machine::GroupState;

/// Opaque MLS group id (32 bytes, generated by OpenMLS).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GroupId(pub [u8; 32]);

/// A single MLS group (1:1 conversations included — a DM is a 2-member group).
pub struct Group {
    /// Protocol group identifier.
    pub id: GroupId,
    /// Current lifecycle state.
    pub state: GroupState,
}

impl Group {
    /// Create a fresh single-member group. The group grows to two
    /// members when the inviter produces a Welcome from the invitee's
    /// KeyPackage.
    pub fn create_solo() -> Result<Self> {
        todo!("openmls::MlsGroup::new with the locked ciphersuite")
    }

    /// Produce a Welcome for `invitee_key_package` and the Commit that
    /// adds them. Returns both; caller is responsible for shipping
    /// Welcome to the invitee and Commit to any existing members.
    pub fn add_member(&mut self, _invitee_key_package: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
        todo!("openmls propose Add + Commit, return (welcome, commit)")
    }

    /// Remove a member. Produces a Commit to distribute.
    pub fn remove_member(&mut self, _member: &PublicKey) -> Result<Vec<u8>> {
        todo!("openmls propose Remove + Commit")
    }

    /// Self-remove (leave group).
    pub fn leave(&mut self) -> Result<Vec<u8>> {
        todo!("openmls self Remove + Commit")
    }

    /// Encrypt an [`Envelope`] into an MLS application message.
    pub fn encrypt(&mut self, _envelope: &Envelope) -> Result<Vec<u8>> {
        todo!("CBOR encode envelope, MlsGroup::create_message")
    }

    /// Decrypt an incoming MLS application message.
    pub fn decrypt(&mut self, _ciphertext: &[u8]) -> Result<Envelope> {
        todo!("MlsGroup::process_message, decode CBOR envelope")
    }
}
