// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Myggiz AB

//! Thin wrapper over `openmls::group::MlsGroup`.

use openmls::prelude::*;

use crate::envelope::Envelope;
use crate::error::{CoreError, Result};
use crate::identity::IdentityKey;
use crate::mls::key_package::{
    credential_with_key, signer_from_identity, KeyPackage, MLS_CIPHERSUITE,
};
use crate::mls::provider::MlsProvider;
use crate::mls::state_machine::GroupState;
use crate::storage::MlsGroupRepo;

/// Opaque MLS group id (variable-length bytes generated by OpenMLS).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GroupId(pub Vec<u8>);

/// Opaque Welcome blob.
pub type WelcomeBytes = Vec<u8>;

/// Opaque Commit blob.
pub type CommitBytes = Vec<u8>;

/// A single MLS group from our perspective.
pub struct Group {
    id: GroupId,
    state: GroupState,
    provider: MlsProvider,
    inner: openmls::group::MlsGroup,
}

impl Group {
    /// Create a fresh single-member group.
    pub(crate) fn create_solo(identity: &IdentityKey, _psk: Option<&[u8; 32]>) -> Result<Self> {
        let provider = MlsProvider::new();
        let signer = signer_from_identity(identity, &provider)?;
        let cwk = credential_with_key(identity, &signer);

        let group_create_config = MlsGroupCreateConfig::builder()
            .ciphersuite(MLS_CIPHERSUITE)
            .use_ratchet_tree_extension(true)
            .build();

        let inner = openmls::group::MlsGroup::new(
            provider.as_openmls(),
            &signer,
            &group_create_config,
            cwk,
        )
        .map_err(|e| CoreError::Mls(format!("mls: builder: {e:?}")))?;

        let gid = GroupId(inner.group_id().to_vec());
        // PSK wiring lands in Task 9; ignored in Task 5.

        Ok(Self {
            id: gid,
            state: GroupState::Active { epoch: 0 },
            provider,
            inner,
        })
    }

    pub(crate) fn add_member(
        &mut self,
        _invitee_kp: &KeyPackage,
        _psk: Option<&[u8; 32]>,
    ) -> Result<(WelcomeBytes, CommitBytes)> {
        todo!("Task 6")
    }

    pub(crate) fn join_from_welcome(
        _identity: &IdentityKey,
        _welcome: &[u8],
        _psk: Option<&[u8; 32]>,
    ) -> Result<Self> {
        todo!("Task 7")
    }

    pub(crate) fn encrypt(&mut self, _envelope: &Envelope) -> Result<Vec<u8>> {
        todo!("Task 8")
    }

    pub(crate) fn decrypt(&mut self, _ciphertext: &[u8]) -> Result<Envelope> {
        todo!("Task 8")
    }

    pub(crate) fn process_incoming_commit(&mut self, _commit: &[u8]) -> Result<()> {
        todo!("Task 10")
    }

    pub(crate) fn advance_epoch(&mut self) -> Result<Vec<u8>> {
        todo!("Task 10")
    }

    /// Persist current state. Writes the `(group_id, state_blob, epoch)`
    /// row via `MlsGroupRepo::put`. `state_blob` is the ciborium-encoded
    /// provider snapshot (HashMap of all OpenMLS internal state).
    pub(crate) fn save(&self, repo: &MlsGroupRepo<'_>) -> Result<()> {
        let blob = self.provider.snapshot()?;
        repo.put(&self.id.0, &blob, self.inner.epoch().as_u64())
    }

    /// Restore from persisted state. Returns `None` if `group_id` is unknown.
    pub(crate) fn load(group_id: &GroupId, repo: &MlsGroupRepo<'_>) -> Result<Option<Self>> {
        let Some(blob) = repo.get(&group_id.0)? else {
            return Ok(None);
        };
        let provider = MlsProvider::load(&blob)?;
        let openmls_gid = openmls::prelude::GroupId::from_slice(&group_id.0);
        let inner = openmls::group::MlsGroup::load(provider.as_openmls().storage(), &openmls_gid)
            .map_err(|e| CoreError::Mls(format!("mls: load: {e:?}")))?
            .ok_or_else(|| CoreError::Mls("mls: load: corrupt state blob".into()))?;

        Ok(Some(Self {
            id: group_id.clone(),
            state: GroupState::Active {
                epoch: inner.epoch().as_u64(),
            },
            provider,
            inner,
        }))
    }

    #[must_use]
    pub fn id(&self) -> &GroupId {
        &self.id
    }

    #[must_use]
    pub fn epoch(&self) -> u64 {
        self.inner.epoch().as_u64()
    }

    #[must_use]
    pub fn state(&self) -> &GroupState {
        &self.state
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::storage::Pool;

    fn alice() -> IdentityKey {
        IdentityKey::generate().unwrap()
    }

    #[test]
    fn create_solo_is_active_at_epoch_0() {
        let id = alice();
        let g = Group::create_solo(&id, None).unwrap();
        assert_eq!(g.epoch(), 0);
        assert!(matches!(g.state(), GroupState::Active { epoch: 0 }));
        assert!(!g.id().0.is_empty(), "group id must be set");
    }

    #[test]
    fn save_load_round_trip_preserves_epoch_and_id() {
        let pool = Pool::in_memory();
        let repo = MlsGroupRepo::new(&pool);
        let id = alice();

        let g = Group::create_solo(&id, None).unwrap();
        let gid = g.id().clone();
        g.save(&repo).unwrap();

        drop(g);

        let restored = Group::load(&gid, &repo).unwrap().expect("must load");
        assert_eq!(restored.epoch(), 0);
        assert_eq!(restored.id(), &gid);
    }

    #[test]
    fn load_missing_group_returns_none() {
        let pool = Pool::in_memory();
        let repo = MlsGroupRepo::new(&pool);
        let gid = GroupId(vec![0x99; 32]);
        assert!(Group::load(&gid, &repo).unwrap().is_none());
    }

    #[test]
    fn load_rejects_corrupt_blob() {
        let pool = Pool::in_memory();
        let repo = MlsGroupRepo::new(&pool);
        let gid = GroupId(vec![0xAA; 32]);
        repo.put(&gid.0, &[0xFFu8; 32], 7).unwrap();
        let err = match Group::load(&gid, &repo) {
            Ok(_) => panic!("garbage must fail"),
            Err(e) => e,
        };
        match err {
            CoreError::Mls(s) => assert!(s.starts_with("mls: load") || s.starts_with("mls:")),
            other => panic!("expected CoreError::Mls, got {other:?}"),
        }
    }
}
