// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Myggiz AB

//! MLS KeyPackage newtype.

use crate::error::Result;
use crate::identity::IdentityKey;
use crate::mls::provider::MlsProvider;

/// A fresh MLS KeyPackage. Generated by the invitee ahead of time,
/// consumed at most once by the inviter's [`crate::mls::Group::add_member`].
pub struct KeyPackage {
    _private: (),
}

impl KeyPackage {
    pub(crate) fn generate(
        _identity: &IdentityKey,
        _provider: &MlsProvider,
        _kp_repo: &crate::storage::KeyPackageRepo<'_>,
    ) -> Result<Self> {
        todo!("Task 4")
    }

    pub(crate) fn to_bytes(&self) -> Result<Vec<u8>> {
        todo!("Task 4")
    }

    pub(crate) fn from_bytes(_bytes: &[u8]) -> Result<Self> {
        todo!("Task 4")
    }

    pub(crate) fn hash(&self) -> [u8; 32] {
        todo!("Task 4")
    }
}
