// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";
import type { PublicKey } from "./PublicKey";

/**
 * Request sent into the daemon.
 */
export type Command = { "cmd": "create_invite", 
/**
 * Optional human-readable nickname embedded in the welcome UX.
 */
nickname: string | null, 
/**
 * Optional TTL in seconds. `None` uses the default (24 h).
 */
ttl_secs: bigint | null, } | { "cmd": "add_contact", 
/**
 * Full `skattr://invite/v1#...` URL.
 */
invite_url: string, } | { "cmd": "list_contacts" } | { "cmd": "send_message", 
/**
 * Recipient identity pubkey.
 */
contact: PublicKey, 
/**
 * Envelope payload.
 */
kind: Kind, } | { "cmd": "recent_messages", 
/**
 * If `Some`, only messages with this peer (either direction).
 */
contact: PublicKey | null, 
/**
 * Max rows to return.
 */
limit: number, } | { "cmd": "create_group", 
/**
 * Initial group members.
 */
members: Array<PublicKey>, 
/**
 * Human-readable group name.
 */
name: string, } | { "cmd": "rotate_onion" } | { "cmd": "shutdown" } | { "cmd": "search_messages", 
/**
 * Free-form FTS5 query string. Whitespace-only queries
 * short-circuit to an empty `SearchResults(vec![])` without
 * hitting FTS5. Malformed queries that reach FTS5 and the
 * engine rejects surface as `DaemonErrorKind::SearchSyntax`.
 */
query: string, 
/**
 * If `Some`, restrict results to messages exchanged with this peer.
 */
contact: PublicKey | null, 
/**
 * Max rows to return (page size).
 */
limit: number, 
/**
 * Number of leading rows to skip (paging cursor).
 */
offset: number, 
/**
 * If `true`, sort newest-first by `ts_daemon_recv`; otherwise FTS rank.
 */
newest_first: boolean, } | { "cmd": "mark_read", 
/**
 * Peer whose conversation cursor is being advanced.
 */
contact: PublicKey, 
/**
 * Message-table `id` (primary key) up to which messages are
 * considered read.
 */
up_to_message_id: bigint, } | { "cmd": "prune_history", 
/**
 * If `Some`, only prune within this peer's conversation.
 */
contact: PublicKey | null, 
/**
 * Delete messages with `ts_daemon_recv < this`. Unix seconds.
 */
before_ts_recv: bigint | null, 
/**
 * Keep at most this many most-recent rows per conversation.
 */
keep_last: bigint | null, } | { "cmd": "add_mailbox", 
/**
 * Operator's onion address (without `:port` suffix).
 */
onion: string, } | { "cmd": "remove_mailbox", 
/**
 * Primary-key `id` of the mailbox row to remove.
 */
id: bigint, } | { "cmd": "list_mailboxes" } | { "cmd": "daemon_info" } | { "cmd": "export_history", 
/**
 * Peer whose history to export.
 */
contact: PublicKey, 
/**
 * Page cursor: return rows with `id > after_id`. `None` starts
 * from the beginning.
 */
after_id: bigint | null, 
/**
 * Max rows per page.
 */
limit: number, };
