// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactSummary } from "./ContactSummary";
import type { Hex16 } from "./Hex16";
import type { Hex32 } from "./Hex32";
import type { MailboxSummary } from "./MailboxSummary";
import type { MessageRecord } from "./MessageRecord";
import type { PublicKey } from "./PublicKey";
import type { SearchHitRecord } from "./SearchHitRecord";
import type { SendStatus } from "./SendStatus";

/**
 * Response returned for a completed [`Command`].
 */
export type CommandResult = { "result": "invite_created", "data": { 
/**
 * Canonical `skattr://invite/v1#...` URL.
 */
url: string, 
/**
 * 32-byte KeyPackage hash (the single-use id).
 */
key_package_id: Hex32, 
/**
 * Unix seconds when the invite expires.
 */
expires_at: bigint, } } | { "result": "contact_added", "data": ContactSummary } | { "result": "contacts", "data": Array<ContactSummary> } | { "result": "message_sent", "data": { 
/**
 * 16-byte per-message id (for correlation with later
 * `Event::DeliveryStatusChanged`).
 */
message_id: Hex16, 
/**
 * Outcome after the inline wait.
 */
status: SendStatus, } } | { "result": "messages", "data": Array<MessageRecord> } | { "result": "subscribed" } | { "result": "ok" } | { "result": "search_results", "data": Array<SearchHitRecord> } | { "result": "marked_read", "data": { 
/**
 * Message-table `id` (primary key) of the highest message marked read.
 */
up_to: bigint, } } | { "result": "pruned", "data": { 
/**
 * Number of message rows actually deleted.
 */
rows_deleted: bigint, } } | { "result": "export_page", "data": { 
/**
 * Records in this page.
 */
records: Array<MessageRecord>, 
/**
 * Cursor for the next page; `None` if this was the last page.
 */
next_after_id: bigint | null, } } | { "result": "mailboxes", "data": Array<MailboxSummary> } | { "result": "daemon_info", "data": { 
/**
 * Local Ed25519 identity pubkey.
 */
local_pubkey: PublicKey, 
/**
 * Current v3 onion address (without `:port`). `None` while
 * Tor is still bootstrapping.
 */
current_onion: string | null, 
/**
 * `env!("CARGO_PKG_VERSION")` of `skattr-core`.
 */
daemon_version: string, 
/**
 * Latest applied storage migration version.
 */
schema_version: number, } };
