// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicKey } from "./PublicKey";

/**
 * Wire-safe projection of a contact row + latest card.
 */
export type ContactSummary = { 
/**
 * Ed25519 identity pubkey.
 */
pubkey: PublicKey, 
/**
 * User-settable local nickname.
 */
nickname: string | null, 
/**
 * Onion address from the latest verified `ContactCard`.
 */
onion: string, 
/**
 * Version of the latest known `ContactCard`.
 */
card_version: bigint, 
/**
 * Unix seconds when the contact was first added locally.
 */
added_at: bigint, 
/**
 * Number of unread messages in this contact's group, counted
 * against the per-group `read_state` cursor. `0` for fresh
 * contacts.
 */
unread_count: bigint, 
/**
 * First ≤80 Unicode code points of the latest message body.
 * `None` when the latest message is not `Kind::Text`, or when
 * the contact has no messages.
 */
last_message_preview: string | null, 
/**
 * `MAX(ts_daemon_recv)` across both directions in this
 * contact's group; `None` if zero messages.
 */
last_ts_recv: bigint | null, };
