// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed categories a CLI can act on.
 */
export type DaemonErrorKind = { "kind": "contact_not_found" } | { "kind": "contact_ambiguous", "data": { 
/**
 * Number of contacts that matched the prefix.
 */
matches: number, } } | { "kind": "invite_expired" } | { "kind": "invite_consumed" } | { "kind": "invite_signature_invalid" } | { "kind": "group_corrupt" } | { "kind": "delivery_timeout" } | { "kind": "tor_not_ready" } | { "kind": "storage_error" } | { "kind": "search_syntax" } | { "kind": "invalid_argument", "data": { 
/**
 * Human-readable description of the argument error.
 */
message: string, } };
