// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-message delivery outcome.
 */
export type DeliveryStatus = "Queued" | "Delivered" | "Deposited" | { "Failed": string };
