// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direction of a stored message relative to the local identity.
 */
export type Direction = "incoming" | "outgoing";
