// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";
import type { MessageId } from "./MessageId";

/**
 * Wire envelope carried inside MLS application messages.
 */
export type Envelope = { 
/**
 * Wire format version. Currently `1`.
 */
v: number, 
/**
 * Per-message id.
 */
id: MessageId, 
/**
 * Sender's wall-clock time, millis since Unix epoch.
 *
 * Display-only. Ordering comes from MLS generation numbers, not from
 * this field. Receivers reject envelopes whose `ts` is more than
 * one hour away from local clock (replay resistance).
 */
ts: bigint, 
/**
 * Optional reply target.
 */
reply_to: MessageId | null, 
/**
 * Payload discriminator and body.
 */
kind: Kind, };
