// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeliveryStatus } from "./DeliveryStatus";
import type { MailboxStatus } from "./MailboxStatus";
import type { MessageId } from "./MessageId";
import type { MessageRecord } from "./MessageRecord";
import type { PublicKey } from "./PublicKey";
import type { TorStatus } from "./TorStatus";

/**
 * Event emitted by the daemon.
 *
 * Adjacently tagged (`tag = "event", content = "data"`) so that
 * ciborium can round-trip newtype variants (e.g. `TorStatusChanged`)
 * without hitting the internally-tagged / non-map-value limitation.
 */
export type Event = { "event": "tor_status_changed", "data": TorStatus } | { "event": "message_received", "data": { 
/**
 * Peer identity pubkey.
 */
contact: PublicKey, 
/**
 * Canonical message-row projection at receive time.
 */
record: MessageRecord, } } | { "event": "contact_updated", "data": PublicKey } | { "event": "delivery_status_changed", "data": { 
/**
 * Message id, mirrors the one returned when the send was queued.
 */
message: MessageId, 
/**
 * Current status.
 */
status: DeliveryStatus, } } | { "event": "mailbox_status_changed", "data": { 
/**
 * Row id from the `mailboxes` table.
 */
mailbox_id: bigint, 
/**
 * New status.
 */
status: MailboxStatus, } } | { "event": "contact_card_received", "data": { 
/**
 * Peer identity pubkey.
 */
contact: PublicKey, 
/**
 * New monotonic version (always strictly greater than the
 * previously-stored card's version, per `ContactRepo::put_card`).
 */
version: bigint, } };
