// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicKey } from "./PublicKey";

/**
 * Subscription filter for `IpcRequest::Subscribe`.
 */
export type EventFilter = { "filter": "all" } | { "filter": "contact", "data": PublicKey } | { "filter": "tor_status" } | { "filter": "messages", "data": { 
/**
 * Optional per-peer narrowing.
 */
contact: PublicKey | null, } } | { "filter": "mailboxes" } | { "filter": "delivery" };
