// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 32-byte hex newtype (backing `PublicKey`, `GroupId`).
 */
export type Hex32 = string;
