// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed variants for invite-layer errors.
 */
export type InviteErrorKind = "Expired" | "Consumed" | "SignatureInvalid" | { "Other": string };
