// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonErrorKind } from "./DaemonErrorKind";

/**
 * Stable wire error. `Daemon(DaemonErrorKind)` carries the library-error
 * projection; `Internal(String)` is a 256-byte-truncated fallback whose
 * full detail stays server-side in tracing logs.
 */
export type IpcError = { "err": "auth_denied" } | { "err": "codec", "data": string } | { "err": "frame_too_large", "data": { 
/**
 * Reported body length.
 */
got: number, 
/**
 * Maximum accepted body length.
 */
max: number, } } | { "err": "unknown_command" } | { "err": "vault_not_ready" } | { "err": "daemon", "data": DaemonErrorKind } | { "err": "internal", "data": string };
