// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Command } from "./Command";
import type { EventFilter } from "./EventFilter";

/**
 * Request frame sent from CLI to daemon.
 */
export type IpcRequest = { "req": "execute", "data": Command } | { "req": "subscribe", "data": EventFilter } | { "req": "shutdown" };
