// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandResult } from "./CommandResult";
import type { Event } from "./Event";
import type { IpcError } from "./IpcError";

/**
 * Response frame sent from daemon to CLI.
 */
export type IpcResponse = { "resp": "ok", "data": CommandResult } | { "resp": "err", "data": IpcError } | { "resp": "event", "data": Event } | { "resp": "bye" };
