// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "./MessageId";

/**
 * Payload discriminator.
 */
export type Kind = { "kind": "text", 
/**
 * Message body.
 */
body: string, } | { "kind": "file", 
/**
 * CBOR-encoded attachment manifest (raw bytes, base64 in JSON contexts).
 */
manifest: string, } | { "kind": "reaction", 
/**
 * Target message id.
 */
target: MessageId, 
/**
 * The emoji, as a short UTF-8 string.
 */
emoji: string, } | { "kind": "edit", 
/**
 * Target message id.
 */
target: MessageId, 
/**
 * New body.
 */
body: string, } | { "kind": "delete", 
/**
 * Target message id.
 */
target: MessageId, } | { "kind": "typing" } | { "kind": "contact_card_update",  };
