// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors the `mailboxes.status` CHECK constraint.
 */
export type MailboxStatus = "unknown" | "reachable" | "unreachable" | "rate_limited" | "pending_removal" | "removed";
