// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxStatus } from "./MailboxStatus";

/**
 * Wire-safe projection of a `mailboxes` row for CLI / UI display.
 */
export type MailboxSummary = { 
/**
 * SQLite primary key of the `mailboxes` row.
 */
id: bigint, 
/**
 * Onion address (without `:port`).
 */
onion: string, 
/**
 * Current lifecycle status.
 */
status: MailboxStatus, 
/**
 * Unix seconds when the row was first created.
 */
registered_at: bigint, };
