// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { Hex16 } from "./Hex16";
import type { Kind } from "./Kind";
import type { PublicKey } from "./PublicKey";

/**
 * Wire-safe projection of a persisted message row.
 */
export type MessageRecord = { 
/**
 * SQLite primary key — stable within one node; used by UI for scroll
 * anchoring, mark_read cursor targeting, and trace correlation.
 */
row_id: bigint, 
/**
 * 16-byte per-message id.
 */
message_id: Hex16, 
/**
 * Peer identity pubkey.
 */
contact: PublicKey, 
/**
 * Incoming or outgoing.
 */
direction: Direction, 
/**
 * Envelope payload.
 */
kind: Kind, 
/**
 * MLS generation number (0 until 1.G/2.x populate it).
 */
mls_generation: bigint, 
/**
 * Authoritative local-clock receive timestamp (unix seconds).
 */
ts_daemon_recv: bigint, 
/**
 * Sender-claimed timestamp — display only (unix seconds signed).
 */
ts_envelope: bigint, };
