// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Random 16-byte per-message identifier.
 *
 * Used for ACK correlation and receiver-side deduplication over a
 * 24-hour sliding window per sender.
 */
export type MessageId = string;
