// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An Ed25519 public key, 32 bytes.
 *
 * `PublicKey` is `Copy` and safe to log in debug output at `trace`
 * level only — pubkeys are sensitive metadata. Display format is
 * hex-encoded; see [`PublicKey::to_hex`].
 *
 * `Ord` / `PartialOrd` derive lexicographic byte order; used for
 * stable display sorts and for deterministic ordering in tests.
 * Not a cryptographic ordering — do not use for security decisions.
 */
export type PublicKey = string;
