// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageRecord } from "./MessageRecord";

/**
 * One full-text search hit returned by `Command::SearchMessages`.
 */
export type SearchHitRecord = { 
/**
 * Underlying message row projection.
 */
record: MessageRecord, 
/**
 * FTS5 BM25 rank score (lower = better; negative is normal for BM25).
 */
bm25: number, 
/**
 * FTS5-rendered snippet around the matched terms.
 */
snippet: string, };
