// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of a `SendMessage` command after the inline-delivery wait.
 */
export type SendStatus = "queued" | "delivered";
