// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tor-layer status, surfaced for UI bootstrap progress bars.
 */
export type TorStatus = "Idle" | { "Bootstrapping": number } | "Ready" | { "Failed": string };
