// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Myggiz B.V.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version. See LICENSE-AGPL3.

//! Arti + tor-hsservice glue (binary-only).
//!
//! Bootstraps the embedded Tor client, publishes a v3 onion service,
//! and pipes every inbound rendezvous stream into
//! [`MailboxServer::accept_loop`].
//!
//! The accept-loop wrapper mirrors `core::transport::listener` from
//! Phase 0.C: drain the rend-request stream, accept each
//! `RendRequest`, then drain its per-circuit `StreamRequest`s and hand
//! the resulting `DataStream` to `accept_loop`. Unlike the core
//! transport, the mailbox does NOT wrap streams in Noise — it serves
//! raw onion streams directly to the framed `MailboxFrameCodec`.

#![cfg(feature = "bin")]

use std::path::Path;
use std::sync::Arc;

use anyhow::{Context, Result};
use arti_client::config::TorClientConfigBuilder;
use arti_client::{TorClient, TorClientConfig};
use futures::StreamExt as _;
use tor_rtcompat::tokio::TokioRustlsRuntime;

use crate::server::MailboxServer;

/// Default on-disk identifier for the onion service. Operators can
/// override via the binary's CLI; this is **not** the public `.onion`
/// address (which is derived from the keystore's HS identity key).
pub const DEFAULT_HS_NICKNAME: &str = "mailbox";

/// Spawned-onion handle. Dropping this handle aborts the accept loop;
/// the embedded `Arc<RunningOnionService>` keeps the descriptor
/// published until its last clone is dropped, so callers should hold
/// this handle for the lifetime of the server.
pub struct OnionListener {
    /// Held to keep the descriptor published. Dropping the last clone
    /// stops publishing and tears down active rendezvous circuits.
    _service: Arc<tor_hsservice::RunningOnionService>,
    /// Background task draining `RendRequest`s; aborted on drop.
    accept_task: tokio::task::JoinHandle<()>,
}

impl Drop for OnionListener {
    fn drop(&mut self) {
        self.accept_task.abort();
    }
}

/// Bring up Arti + a v3 onion service, then forward each inbound
/// rendezvous stream to `server.accept_loop` in its own task.
///
/// Returns once the descriptor has been launched (not necessarily
/// uploaded — Arti uploads asynchronously). The background accept loop
/// lives on the returned `OnionListener` handle; drop it to tear down
/// the service.
///
/// The Tor identity key is generated by Arti on first launch and
/// persisted under `arti_state_dir/keystore`, so the resulting
/// `.onion` address is stable across restarts as long as the state
/// directory survives.
pub async fn run_onion(
    arti_state_dir: &Path,
    nickname: &str,
    server: Arc<MailboxServer>,
) -> Result<OnionListener> {
    std::fs::create_dir_all(arti_state_dir).context("create arti state dir")?;
    let cache_dir = arti_state_dir.join("cache");
    std::fs::create_dir_all(&cache_dir).context("create arti cache dir")?;

    // Arti 0.41 refuses to open a state_dir or cache_dir that is
    // group- or world-readable; default umask leaves them at 0755 so
    // we must chmod to 0700 ourselves. systemd's `StateDirectory`
    // also defaults to 0755 so this is a production fix, not just a
    // test workaround.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        for path in [arti_state_dir, cache_dir.as_path()] {
            let mut perms = std::fs::metadata(path)
                .with_context(|| format!("stat {}", path.display()))?
                .permissions();
            perms.set_mode(0o700);
            std::fs::set_permissions(path, perms)
                .with_context(|| format!("chmod 0700 {}", path.display()))?;
        }
    }

    // `from_directories` is the idiomatic 0.41 builder; mirrors
    // `core::transport::tor::TorRuntime::bootstrap`.
    let tor_config: TorClientConfig =
        TorClientConfigBuilder::from_directories(arti_state_dir, &cache_dir)
            .build()
            .context("arti config")?;

    let runtime = TokioRustlsRuntime::current().context("arti runtime: requires tokio reactor")?;

    let tor: TorClient<TokioRustlsRuntime> = TorClient::with_runtime(runtime)
        .config(tor_config)
        .create_unbootstrapped_async()
        .await
        .context("arti client create")?;

    tor.bootstrap().await.context("arti bootstrap")?;

    let nickname_parsed = nickname
        .parse::<tor_hsservice::HsNickname>()
        .with_context(|| format!("invalid HS nickname '{nickname}'"))?;

    let hs_cfg = tor_hsservice::config::OnionServiceConfigBuilder::default()
        .nickname(nickname_parsed)
        .build()
        .context("HS config")?;

    let (svc, rend_requests) = tor
        .launch_onion_service(hs_cfg)
        .context("launch onion service")?
        .context("HS disabled in arti config")?;

    // Log the public `.onion` address. `HsId` requires opting into
    // un-redacted display via `safelog`; we do so deliberately because
    // the address is meant to be shared with clients.
    if let Some(addr) = svc.onion_address() {
        use safelog::DisplayRedacted as _;
        tracing::info!(onion = %addr.display_unredacted(), "mailbox onion published");
    } else {
        tracing::warn!("mailbox onion launched but has no address yet");
    }

    let server_for_task = server.clone();
    let accept_task = tokio::spawn(async move {
        tokio::pin!(rend_requests);
        while let Some(rend_req) = rend_requests.next().await {
            // Accept the rendezvous (negotiates the rendezvous circuit).
            // 0.41: `RendRequest::accept` is async and returns
            // `Result<impl Stream<Item = StreamRequest>, _>`.
            let stream_requests = match rend_req.accept().await {
                Ok(s) => s,
                Err(e) => {
                    tracing::warn!(error = %e, "HS rend request: accept failed");
                    continue;
                }
            };
            let mut stream_requests = stream_requests;
            while let Some(stream_req) = stream_requests.next().await {
                // Each per-circuit StreamRequest must be accepted with a
                // `Connected` cell. An empty Connected (no address) is
                // the correct response for a hidden service: the client
                // already knows the destination it dialled.
                let connected = tor_cell::relaycell::msg::Connected::new_empty();
                let data_stream = match stream_req.accept(connected).await {
                    Ok(ds) => ds,
                    Err(e) => {
                        tracing::warn!(error = %e, "HS stream request: accept failed");
                        continue;
                    }
                };
                let server_per_stream = server_for_task.clone();
                tokio::spawn(async move {
                    if let Err(e) = server_per_stream.serve_connection(data_stream).await {
                        tracing::warn!(error = %e, "mailbox serve_connection returned error");
                    }
                });
            }
        }
    });

    Ok(OnionListener {
        _service: svc,
        accept_task,
    })
}
