// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Myggiz B.V.

#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

//! Send-side metadata stripping for common image formats. Non-image / unknown
//! types pass through unchanged. v1.0 scope: image EXIF/metadata; PDF/document
//! metadata is deferred (v1.1).
//!
//! Detection sniffs magic bytes first (authoritative); the declared MIME is
//! only a fallback. A sender that *claims* an image MIME but ships malformed
//! bytes is rejected with [`AttachmentErrorKind::StripFailed`] rather than
//! silently passed through, so we never relay metadata we failed to inspect.

use bytes::Bytes;
use img_parts::png::{Png, PngChunk};
use img_parts::{ImageEXIF, ImageICC};

use crate::attachment::error_kind::AttachmentErrorKind;
use crate::error::Result;

enum ImageKind {
    Jpeg,
    Png,
    Other,
}

fn detect_kind(bytes: &[u8], mime: &str) -> ImageKind {
    // Sniff magic bytes first (authoritative), fall back to mime.
    if bytes.starts_with(&[0xFF, 0xD8, 0xFF]) || mime == "image/jpeg" {
        ImageKind::Jpeg
    } else if bytes.starts_with(&[0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
        || mime == "image/png"
    {
        ImageKind::Png
    } else {
        ImageKind::Other
    }
}

/// Strip metadata from supported image types; pass others through unchanged.
/// Returns `(bytes, effective_mime)`.
pub(crate) fn strip_metadata(bytes: &[u8], mime: &str) -> Result<(Vec<u8>, String)> {
    match detect_kind(bytes, mime) {
        ImageKind::Jpeg => Ok((strip_jpeg(bytes)?, "image/jpeg".to_string())),
        ImageKind::Png => Ok((strip_png(bytes)?, "image/png".to_string())),
        ImageKind::Other => Ok((bytes.to_vec(), mime.to_string())),
    }
}

/// PNG ancillary chunks that can carry metadata / fingerprinting surface. We
/// drop these wholesale in addition to the EXIF/ICC trait removals below.
/// Critical chunks (IHDR/PLTE/IDAT/IEND) and rendering-essential ancillary
/// chunks (gamma, chroma, etc.) are retained so the pixels decode unchanged.
const PNG_METADATA_CHUNKS: &[[u8; 4]] = &[
    *b"tEXt", // Latin-1 textual data
    *b"zTXt", // compressed textual data
    *b"iTXt", // international (UTF-8) textual data
    *b"eXIf", // embedded EXIF
    *b"tIME", // last-modification time
    *b"iCCP", // ICC profile (also cleared via set_icc_profile)
];

fn strip_jpeg(bytes: &[u8]) -> Result<Vec<u8>> {
    let mut jpeg = img_parts::jpeg::Jpeg::from_bytes(Bytes::copy_from_slice(bytes))
        .map_err(|e| AttachmentErrorKind::StripFailed(format!("jpeg parse: {e}")))?;

    // Remove EXIF (APP1) and any ICC profile (APP2). These are the metadata
    // surfaces img-parts exposes structurally; the SOF/SOS pixel segments and
    // entropy data are left untouched.
    jpeg.set_exif(None);
    jpeg.set_icc_profile(None);

    Ok(jpeg.encoder().bytes().to_vec())
}

fn strip_png(bytes: &[u8]) -> Result<Vec<u8>> {
    let mut png = Png::from_bytes(Bytes::copy_from_slice(bytes))
        .map_err(|e| AttachmentErrorKind::StripFailed(format!("png parse: {e}")))?;

    png.set_exif(None);
    png.set_icc_profile(None);

    let is_metadata_chunk: fn(&PngChunk) -> bool =
        |chunk| PNG_METADATA_CHUNKS.iter().any(|k| *k == chunk.kind());
    png.chunks_mut().retain(|chunk| !is_metadata_chunk(chunk));

    Ok(png.encoder().bytes().to_vec())
}

#[cfg(test)]
mod tests {
    use super::*;
    use img_parts::jpeg::Jpeg;

    /// A 1x1 baseline JPEG (no EXIF) used as the base for building fixtures.
    /// Generated by encoding a 1x1 black pixel; checked for determinism.
    const BASE_JPEG: &[u8] = include_bytes!("../../tests/fixtures/base.jpg");

    /// Build a JPEG carrying an APP1/EXIF segment from the base fixture.
    fn jpeg_with_exif() -> Vec<u8> {
        let mut jpeg = Jpeg::from_bytes(Bytes::copy_from_slice(BASE_JPEG)).unwrap();
        // A tiny but well-formed EXIF payload: TIFF header (little-endian) +
        // an empty IFD0. img-parts prefixes the "Exif\0\0" marker itself.
        let exif: &[u8] = &[
            0x49, 0x49, 0x2A, 0x00, // II, 42 (little-endian TIFF)
            0x08, 0x00, 0x00, 0x00, // offset to IFD0
            0x00, 0x00, // IFD0 entry count = 0
        ];
        jpeg.set_exif(Some(Bytes::copy_from_slice(exif)));
        jpeg.encoder().bytes().to_vec()
    }

    /// True if the JPEG carries an APP1/EXIF segment.
    fn has_exif(bytes: &[u8]) -> bool {
        Jpeg::from_bytes(Bytes::copy_from_slice(bytes))
            .map(|j| j.exif().is_some())
            .unwrap_or(false)
    }

    #[test]
    fn base_fixture_is_a_valid_exif_free_jpeg() {
        // Guards the checked-in fixture: parses, has SOI, no EXIF to start.
        assert_eq!(&BASE_JPEG[..2], &[0xFF, 0xD8]);
        assert!(Jpeg::from_bytes(Bytes::copy_from_slice(BASE_JPEG)).is_ok());
        assert!(!has_exif(BASE_JPEG));
        // Sanity: it has enough segments for set_exif's insert(3).
        let j = Jpeg::from_bytes(Bytes::copy_from_slice(BASE_JPEG)).unwrap();
        assert!(j.segments().len() >= 3, "base needs >=3 segments");
    }

    #[test]
    fn strips_exif_from_jpeg() {
        let input = jpeg_with_exif();
        assert!(has_exif(&input), "fixture must start with EXIF");
        let (stripped, mime) = strip_metadata(&input, "image/jpeg").unwrap();
        assert_eq!(mime, "image/jpeg");
        assert!(!has_exif(&stripped), "EXIF must be gone after strip");
        // still a valid JPEG (SOI marker intact)
        assert_eq!(&stripped[..2], &[0xFF, 0xD8]);
    }

    #[test]
    fn strips_exif_when_mime_lies_but_magic_is_jpeg() {
        // Sender declares octet-stream but ships a real EXIF JPEG: magic wins,
        // metadata is still stripped.
        let input = jpeg_with_exif();
        assert!(has_exif(&input));
        let (stripped, mime) = strip_metadata(&input, "application/octet-stream").unwrap();
        assert_eq!(mime, "image/jpeg");
        assert!(!has_exif(&stripped));
    }

    #[test]
    fn strips_icc_segment_from_jpeg() {
        // Build a JPEG with both EXIF and a junk APP2/ICC segment.
        let mut jpeg = Jpeg::from_bytes(Bytes::copy_from_slice(BASE_JPEG)).unwrap();
        jpeg.set_icc_profile(Some(Bytes::from_static(&[1, 2, 3, 4, 5, 6, 7, 8])));
        let input = jpeg.encoder().bytes().to_vec();
        let reparsed = Jpeg::from_bytes(Bytes::copy_from_slice(&input)).unwrap();
        assert!(reparsed.icc_profile().is_some(), "fixture must carry ICC");

        let (stripped, _) = strip_metadata(&input, "image/jpeg").unwrap();
        let out = Jpeg::from_bytes(Bytes::copy_from_slice(&stripped)).unwrap();
        assert!(out.icc_profile().is_none(), "ICC must be gone after strip");
    }

    #[test]
    fn malformed_image_claiming_jpeg_mime_is_rejected() {
        // Magic doesn't match JPEG, but the declared mime does -> we treat it
        // as JPEG, fail to parse, and reject (no silent passthrough).
        let junk = b"this is definitely not a jpeg".to_vec();
        let err = strip_metadata(&junk, "image/jpeg").unwrap_err();
        assert!(matches!(
            err,
            crate::error::CoreError::Attachment(AttachmentErrorKind::StripFailed(_))
        ));
    }

    #[test]
    fn malformed_image_claiming_png_mime_is_rejected() {
        let junk = b"not a png either".to_vec();
        let err = strip_metadata(&junk, "image/png").unwrap_err();
        assert!(matches!(
            err,
            crate::error::CoreError::Attachment(AttachmentErrorKind::StripFailed(_))
        ));
    }

    #[test]
    fn passes_through_non_image() {
        let bytes = b"not an image".to_vec();
        let (out, mime) = strip_metadata(&bytes, "application/octet-stream").unwrap();
        assert_eq!(out, bytes);
        assert_eq!(mime, "application/octet-stream");
    }

    #[test]
    fn strips_text_chunks_from_png() {
        // Minimal 1x1 PNG, then append a tEXt chunk before IEND.
        let base = include_bytes!("../../tests/fixtures/base.png");
        let mut png = Png::from_bytes(Bytes::copy_from_slice(base)).unwrap();
        let mut text = Vec::new();
        text.extend_from_slice(b"Comment\0fingerprint");
        let chunk = PngChunk::new(*b"tEXt", Bytes::from(text));
        // Insert the tEXt chunk just before IEND (the last chunk).
        let len = png.chunks().len();
        png.chunks_mut().insert(len - 1, chunk);
        let input = png.encoder().bytes().to_vec();

        let has_text = |b: &[u8]| {
            Png::from_bytes(Bytes::copy_from_slice(b))
                .map(|p| p.chunk_by_type(*b"tEXt").is_some())
                .unwrap_or(false)
        };
        assert!(has_text(&input), "fixture must carry a tEXt chunk");

        let (stripped, mime) = strip_metadata(&input, "image/png").unwrap();
        assert_eq!(mime, "image/png");
        assert!(!has_text(&stripped), "tEXt must be gone after strip");
        assert_eq!(&stripped[..4], &[0x89, 0x50, 0x4E, 0x47]);
    }
}
